# Generated by Django 6.0.4 on 2026-04-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgs_id', models.CharField(max_length=50, unique=True)),
                ('magnitude', models.FloatField()),
                ('depth', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('source', models.CharField(default='USGS', max_length=50)),
            ],
        ),
    ]
